#DROP DATABASE SNAKEGAME;
CREATE DATABASE LOA;
USE LOA;

# DROP TABLE ADVENTURE_ISLAND;
CREATE TABLE ADVENTURE_ISLAND(
	`ID` INT NOT NULL,
    `ISLAND` VARCHAR(50) NOT NULL,
    `REWARD` VARCHAR(50) NOT NULL,
    PRIMARY KEY(`id`)
);

# ADVENTURE_ISLAND
INSERT INTO ADVENTURE_ISLAND (`ID`, `ISLAND`, `REWARD`) VALUES(20230127, '하모니 섬,죽음의 협곡,고요한 안식의 섬', '카드,실링,골드');
INSERT INTO ADVENTURE_ISLAND (`ID`, `ISLAND`, `REWARD`) VALUES(20230128, '기회의 섬,메데이아,잔혹한 장난감 성,수라도,스노우팡 아일랜드,쿵덕쿵 아일랜드', '주화,카드,실링,카드,주화,실링');
INSERT INTO ADVENTURE_ISLAND (`ID`, `ISLAND`, `REWARD`) VALUES(20230129, '환영 나비 섬,고요한 안식의 섬,쿵덕쿵 아일랜드,볼라르 섬,우거진 갈대의 섬,기회의 섬', '주화,카드,실링,카드,실링,골드');
INSERT INTO ADVENTURE_ISLAND (`ID`, `ISLAND`, `REWARD`) VALUES(20230130, '메데이아,포르페,죽음의 협곡', '카드,카드,주화');
INSERT INTO ADVENTURE_ISLAND (`ID`, `ISLAND`, `REWARD`) VALUES(20230131, '블루홀 섬,하모니 섬,잔혹한 장난감 섬', '주화,실링,카드');

INSERT INTO ADVENTURE_ISLAND (`ID`, `ISLAND`, `REWARD`) VALUES(20230201, '스노우팡 아일랜드,몬테섬,잔혹한 장난감 성', '실링,카드,카드');
INSERT INTO ADVENTURE_ISLAND (`ID`, `ISLAND`, `REWARD`) VALUES(20230202, '고요한 안식의 섬,포르페,블루홀 섬', '실링,카드,주화');

# DELETE FROM ADVENTURE_ISLAND WHERE `ID` = 20230127;

SELECT * FROM ADVENTURE_ISLAND;



# DROP TABLE ISLAND_CALENDER;
CREATE TABLE ISLAND_CALENDER(
	`DATE` INT NOT NULL,
    `ISLAND` VARCHAR(50) NOT NULL,
    `REWARD` VARCHAR(50) NOT NULL,
    `TYPE` INT DEFAULT 0, # 0 - 주간 / 1 - 주말(오전) / 2 - 주말(오후)
    PRIMARY KEY(`DATE`, `ISLAND`)
);


# ISLAND_CALENDER
INSERT INTO ISLAND_CALENDER (`DATE`, `ISLAND`, `REWARD`, `TYPE`) VALUES(20230127, '하모니 섬', '카드', 0);
INSERT INTO ISLAND_CALENDER (`DATE`, `ISLAND`, `REWARD`, `TYPE`) VALUES(20230127, '죽음의 협곡', '실링', 0);
INSERT INTO ISLAND_CALENDER (`DATE`, `ISLAND`, `REWARD`, `TYPE`) VALUES(20230127, '고요한 안식의 섬', '골드', 0);
INSERT INTO ISLAND_CALENDER (`DATE`, `ISLAND`, `REWARD`, `TYPE`) VALUES(20230128, '기회의 섬', '주화', 1);
INSERT INTO ISLAND_CALENDER (`DATE`, `ISLAND`, `REWARD`, `TYPE`) VALUES(20230128, '메데이아', '카드', 1);
INSERT INTO ISLAND_CALENDER (`DATE`, `ISLAND`, `REWARD`, `TYPE`) VALUES(20230128, '잔혹한 장난감 성', '실링', 1);
INSERT INTO ISLAND_CALENDER (`DATE`, `ISLAND`, `REWARD`, `TYPE`) VALUES(20230128, '수라도', '카드', 2);
INSERT INTO ISLAND_CALENDER (`DATE`, `ISLAND`, `REWARD`, `TYPE`) VALUES(20230128, '스노우팡 아일랜드', '주화', 2);
INSERT INTO ISLAND_CALENDER (`DATE`, `ISLAND`, `REWARD`, `TYPE`) VALUES(20230128, '쿵덕쿵 아릴랜드', '실링', 2);
INSERT INTO ISLAND_CALENDER (`DATE`, `ISLAND`, `REWARD`, `TYPE`) VALUES(20230129, '환영 나비 섬', '주화', 1);
INSERT INTO ISLAND_CALENDER (`DATE`, `ISLAND`, `REWARD`, `TYPE`) VALUES(20230129, '고요한 안식의 섬', '카드', 1);
INSERT INTO ISLAND_CALENDER (`DATE`, `ISLAND`, `REWARD`, `TYPE`) VALUES(20230129, '쿵덕쿵 아일랜드', '실링', 1);
INSERT INTO ISLAND_CALENDER (`DATE`, `ISLAND`, `REWARD`, `TYPE`) VALUES(20230129, '볼라르 섬', '카드', 2);
INSERT INTO ISLAND_CALENDER (`DATE`, `ISLAND`, `REWARD`, `TYPE`) VALUES(20230129, '우거진 갈대의 섬', '실링', 2);
INSERT INTO ISLAND_CALENDER (`DATE`, `ISLAND`, `REWARD`, `TYPE`) VALUES(20230129, '기회의 섬', '골드', 2);
INSERT INTO ISLAND_CALENDER (`DATE`, `ISLAND`, `REWARD`, `TYPE`) VALUES(20230130, '메데이아', '카드', 0);
INSERT INTO ISLAND_CALENDER (`DATE`, `ISLAND`, `REWARD`, `TYPE`) VALUES(20230130, '포르페', '카드', 0);
INSERT INTO ISLAND_CALENDER (`DATE`, `ISLAND`, `REWARD`, `TYPE`) VALUES(20230130, '죽음의 협곡', '주화', 0);
INSERT INTO ISLAND_CALENDER (`DATE`, `ISLAND`, `REWARD`, `TYPE`) VALUES(20230131, '블루홀 섬', '주화', 0);
INSERT INTO ISLAND_CALENDER (`DATE`, `ISLAND`, `REWARD`, `TYPE`) VALUES(20230131, '하모니 섬', '실링', 0);
INSERT INTO ISLAND_CALENDER (`DATE`, `ISLAND`, `REWARD`, `TYPE`) VALUES(20230131, '잔혹한 장난감 섬', '카드', 0);

INSERT INTO ISLAND_CALENDER (`DATE`, `ISLAND`, `REWARD`, `TYPE`) VALUES(20230201, '', '', 0);

SELECT * FROM ISLAND_CALENDER;
# DELETE FROM ISLAND_CALENDER WHERE `DATE` = 20230201;





