#DROP DATABASE SNAKEGAME;
CREATE DATABASE LOA;
USE LOA;

CREATE TABLE ADVENTURE_ISLAND(
	`ID` INT NOT NULL,
    `ISLAND` JSON NOT NULL,
    `REWARD` JSON NOT NULL,
    PRIMARY KEY(`id`)
);

INSERT INTO ADVENTURE_ISLAND (`ID`, `ISLAND`, `REWARD`) VALUES('20230127', '["하모니 섬", "죽음의 협곡", "고요한 안식의 섬"]', '["카드", "실링", "골드"]');